import { ArrowLeft, ArrowRight, ExternalLink, GitBranch } from 'lucide-react'
import { Container } from '../components/Container'
import { PageTransition } from '../components/PageTransition'
import { ProjectMedia } from '../components/ProjectCard'
import { portfolio } from '../data/portfolio'

export function ProjectDetailPage({slug}:{slug:string}) {
  const index=portfolio.projects.findIndex(project=>project.slug===slug)
  if(index<0)return <PageTransition><main className="project-not-found"><Container><p className="eyebrow">404 / Project not found</p><h1>That project isn’t in the archive.</h1><a href="/projects"><ArrowLeft size={16} aria-hidden/> Back to projects</a></Container></main></PageTransition>
  const project=portfolio.projects[index], previous=index>0?portfolio.projects[index-1]:null, next=index<portfolio.projects.length-1?portfolio.projects[index+1]:null
  const sections=[['Problem statement',project.details.problem],['What was built',project.details.built],['Technical implementation',project.details.implementation],['Challenges',project.details.challenges],['Result / outcome',project.details.outcome]]
  return <PageTransition><a className="skip-link" href="#project-case-study">Skip to case study</a><header className="projects-page-nav"><Container><a href="/projects"><ArrowLeft size={16} aria-hidden/> Back to projects</a><span>{project.category} / {project.year}</span></Container></header><main className="project-detail" id="project-case-study"><Container><header className="project-detail-header"><div><p className="eyebrow">{project.category} / {project.year}</p><h1>{project.title}</h1></div><p>{project.summary}</p></header><div className="project-detail-hero"><ProjectMedia project={project} index={index} interactive={false}/></div><div className="project-detail-layout"><aside><p>Technologies</p><ul>{project.disciplines.map(item=><li key={item}>{item}</li>)}</ul><div>{project.github&&<a href={project.github} target="_blank" rel="noreferrer"><GitBranch size={15} aria-hidden/>GitHub</a>}{project.liveDemo&&<a href={project.liveDemo} target="_blank" rel="noreferrer"><ExternalLink size={15} aria-hidden/>Live demo</a>}</div></aside><div className="case-study-sections">{sections.map(([title,copy],sectionIndex)=><section key={title}><span>{String(sectionIndex+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}</div></div><section className="project-gallery" aria-labelledby="gallery-title"><p className="eyebrow">Additional images</p><h2 id="gallery-title">Project gallery</h2>{project.details.additionalImages.length?<div>{project.details.additionalImages.map((image,imageIndex)=><img src={image} alt={`${project.title} project view ${imageIndex+1}`} loading="lazy" decoding="async" width={1200} height={900} key={image}/>)}</div>:<div className="gallery-empty">Additional project visuals can be added here when the work is ready to be published externally.</div>}</section><nav className="project-siblings" aria-label="Project navigation">{previous?<a href={`/projects/${previous.slug}`}><ArrowLeft aria-hidden/><span>Previous project<strong>{previous.title}</strong></span></a>:<span/>}{next&&<a href={`/projects/${next.slug}`}><span>Next project<strong>{next.title}</strong></span><ArrowRight aria-hidden/></a>}</nav></Container></main></PageTransition>
}
